package com.mycompany.projaula1_exercicio1;

import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author Madianita Bogo
 */
public class FormSomaVetor extends javax.swing.JFrame {
    private int[] vetor;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSomaVetor.class.getName());

    /**
     * Creates new form FormLeArquivos
     */
    public FormSomaVetor() {
        initComponents();
    }          
    
    private void log(String msg) { 
        taSaida.append(msg + "\n"); 
    }

    private void esperarFim(ExecutorService executor, ArrayList<Tarefa> tarefas,long tempoInicio) {
        // Cria uma thread apenas para aguardar o término do Pool,
        // evitando travar a interface gráfica.
        Thread threadEspera = new Thread(new Runnable() {
           @Override
            public void run() {
                try {
                    // Aguarda todas as tarefas enviadas ao Pool terminarem.
                    // O shutdown() já foi chamado antes deste método.
                    executor.awaitTermination(Long.MAX_VALUE,TimeUnit.NANOSECONDS);
                } catch (InterruptedException e) {
                    System.out.println("Erro ao aguardar as tarefas.");
                }

                long somaTotal = 0;
                log("");

                // Todas as tarefas já terminaram. A seguir vem a consulta dos resultados.
                for (int i = 0; i < tarefas.size(); i++) {
                    Tarefa tarefa = tarefas.get(i);                    
                    log("Tarefa " + (i + 1));
                    log("Índices: " + tarefa.getInicio() + " até " + (tarefa.getFim() - 1));
                    log("Soma parcial: "+ tarefa.getSomaParcial());
                    log("Tempo: " + tarefa.getTempo() + " µs");
                    log("");

                    // Soma os resultados parciais
                    somaTotal += tarefa.getSomaParcial();
                }

                // Calcula o tempo total da execução paralela
                long tempoTotal = (System.nanoTime()- tempoInicio)/1000; //converte de nano para microsegundos
                log("Soma total: " + somaTotal);
                log("Tempo total paralelo: " + tempoTotal + " µs");
            }
        });

        threadEspera.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfTamanho = new javax.swing.JTextField();
        btnParalelo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cbxThreads = new javax.swing.JComboBox<>();
        btnSequencial = new javax.swing.JButton();
        btnGerarVetor = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca em Arquivos");

        jLabel1.setText("Tamanho do vetor: ");

        btnParalelo.setBackground(new java.awt.Color(0, 0, 204));
        btnParalelo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnParalelo.setForeground(new java.awt.Color(255, 255, 255));
        btnParalelo.setText("Exec. Paralelo");
        btnParalelo.addActionListener(this::btnParaleloActionPerformed);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        jLabel2.setText("Quantidade de threads: ");

        cbxThreads.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        btnSequencial.setBackground(new java.awt.Color(0, 0, 204));
        btnSequencial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSequencial.setForeground(new java.awt.Color(255, 255, 255));
        btnSequencial.setText("Executar sequencial");
        btnSequencial.addActionListener(this::btnSequencialActionPerformed);

        btnGerarVetor.setBackground(new java.awt.Color(0, 0, 204));
        btnGerarVetor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGerarVetor.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarVetor.setText("Gerar Vetor");
        btnGerarVetor.addActionListener(this::btnGerarVetorActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGerarVetor, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addComponent(btnParalelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSequencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarVetor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxThreads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParalelo))
                .addGap(18, 18, 18)
                .addComponent(btnSequencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParaleloActionPerformed
        // Quantidade de threads escolhida pelo usuário
        int qtdThreads = Integer.parseInt(
                cbxThreads.getSelectedItem().toString());

        log("");
        log("===== EXECUÇÃO PARALELA =====");
        log("Quantidade de threads: " + qtdThreads);
        
        // Início da medição do tempo total
        long tempoInicio = System.nanoTime();

        // Divide o vetor conforme a quantidade de threads
        int tamanhoParte = vetor.length / qtdThreads;

        // Guarda as tarefas para obter os resultados depois
        ArrayList<Tarefa> tarefas = new ArrayList<>();

        // Cria o pool com a quantidade de threads que o usuário solicitou
        ExecutorService executor = Executors.newFixedThreadPool(qtdThreads);

        for (int i = 0; i < qtdThreads; i++) {
            int inicio = i * tamanhoParte;            
            int fim = (i == qtdThreads - 1) ? vetor.length : inicio + tamanhoParte; //última thread fica com o resto do vetor

            // Cria a tarefa responsável por uma parte do vetor
            Tarefa tarefa = new Tarefa(vetor, inicio, fim);

            tarefas.add(tarefa);

            // Envia a tarefa para o Pool.
            // Uma das threads disponíveis será responsável por executá-la.
            executor.submit(tarefa);
        }

        // Não serão enviadas novas tarefas ao pool
        executor.shutdown();

        // Aguarda o término e apresenta os resultados
        esperarFim(executor, tarefas, tempoInicio);
    }//GEN-LAST:event_btnParaleloActionPerformed

    private void btnSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSequencialActionPerformed
        long inicio = System.nanoTime();

        long soma = 0;

        for (int i = 0; i < vetor.length; i++) {
            soma += (long) vetor[i]*vetor[i]*vetor[i]; //soma do cubo do de cada elemento do vetor 
        }

        // Tempo decorrido convertido de nano para microssegundos
        long tempo = (System.nanoTime() - inicio) / 1000;

        log("");
        log("===== EXECUÇÃO SEQUENCIAL =====");
        log("Soma total: " + soma);
        log("Tempo: " + tempo + " µs");
    }//GEN-LAST:event_btnSequencialActionPerformed

    private void btnGerarVetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarVetorActionPerformed
        int tamanho = Integer.parseInt(tfTamanho.getText());

        vetor = new int[tamanho];

        Random random = new Random();

        for (int i = 0; i < vetor.length; i++) {
            vetor[i] = random.nextInt(100);
        }

        taSaida.setText("");

        log("Vetor gerado com " + tamanho + " elementos.");  
    }//GEN-LAST:event_btnGerarVetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormSomaVetor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarVetor;
    private javax.swing.JButton btnParalelo;
    private javax.swing.JButton btnSequencial;
    private javax.swing.JComboBox<String> cbxThreads;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    private javax.swing.JTextField tfTamanho;
    // End of variables declaration//GEN-END:variables
}
